### ISSUE TITLE
Hope to add xformers

### ISSUE THREAD

**Issue by sdbds** [rohitgandikota/sliders#1]
Thank u for great work!
i had noticed last paers ESD in April,and i used LECO like sliders by adjusting CFG.
This is Augest article about LECO my written.
https://civitai.com/articles/1766

I think sliders is more faster and effiect than normal finetune.
but even in LECO, train SDXL use about 20GB VRAM when use xformers, i think this repo need xformers to save VRAM.

**Comment by rohitgandikota** [comment]
Awesome article on LECO! We have released a faster and less computationally expensive version here. xformers would definitely help further. Keeping it open and we will try to add this option.

**Comment by quixot1c** [comment]
I am running the code locally and I had to install xformers because it was missing it. In the config for training 1.x models it says 
`
other:
  use_xformers: true
`
so I'm pretty sure training uses xformers already.

**Comment by rohitgandikota** [comment]
Yes! We did start out with using xformers. But I believe some of the features are not written to support xformers. We are looking into it

**Comment by rohitgandikota** [comment]
xformers is working now - could you do `pip install xformers` and try again by editing config_file to `use_xformers: true`
