### ISSUE TITLE
Composing Sliders

### ISSUE THREAD

**Issue by AdvaithVellanki** [rohitgandikota/sliders#104]
Hi,

I am training multiple text sliders such as age, smile, muscular, etc with the next step being composing them. I was wondering how exactly to proceed with the composition of the sliders. 

Which is the command to run for this?

Looking forward for your reply.

**Comment by rohitgandikota** [comment]
Here is a solution I posted on a similar issue: https://github.com/rohitgandikota/sliders/issues/45#issuecomment-1879295588
