### ISSUE TITLE
Composing Sliders

### ISSUE THREAD

**Issue by AdvaithVellanki** [rohitgandikota/sliders#106]
Hi, sorry for the repeated issue,

i tried implementing the solution in comment #45 , but that led to errors. 

These errors arose when i tried to run it with the pretrained sliders on the paper's page.

For ex, for the 2D composition, when i load age and smile slider, and try to run the contextlib code above, this is the error i am getting:
in :16 │
│ in generate_2d_sliders:418
RuntimeError: Error(s) in loading state_dict for LoRANetwork:
Unexpected key(s) in state_dict: "lora_unet_down_blocks_0_resnets_0_conv1.alpha",
"lora_unet_down_blocks_0_resnets_0_conv1.lora_down.weight",
.
.
.

This error arises in the generate_2d_sliders function, when it tries to the load the weights from the pretrained sliders in line:
networks[i].load_state_dict(torch.load(lora_weights[i]))

Any idea on why it isn't working with the pretrained lora slider? As a sidenote, i tried running the code with loading SDXL turbo as well as the SDXL base model mentioned in the training file incase it was an issue related to different models, but i still got the same issue. 
This issue did not arise when i ran inference on the same pretrained model using XL-Sliders_inference.ipynb

Hoping to hear back from you soon.

**Comment by rohitgandikota** [comment]
this looks like both your sliders are trained using different training methods and ranks. Please make sure that you load them properly and then compose. When you use the compose code I shared, make sure that you change the loading of the modules according to your models. That seems to be the issue

**Comment by AdvaithVellanki** [comment]
Thanks for the prompt reply. It is working now, Does the same code mentioned in #45 allow for the generation of the grid of compositions, like the image shown in the paper for cooked and fine-dining? Or is that another implementation?
