### ISSUE TITLE
use in real images?

### ISSUE THREAD

**Issue by loboere** [rohitgandikota/sliders#11]
Is there any way to use it on real images?

**Comment by rohitgandikota** [comment]
Yes!! We are working on a demo for real image editing. Will be out soon.

**Comment by rohitgandikota** [comment]
The demo is out!! : https://github.com/rohitgandikota/sliders/blob/main/demo_image_editing.ipynb

**Comment by loboere** [comment]
Great, are you planning to release one for sdxl?
