### ISSUE TITLE
Huggingface Demo failed

### ISSUE THREAD

**Issue by buxiangzhiren** [rohitgandikota/sliders#115]
Hi, thank you for sharing your excellent work!

When I wanted to use your hugging face demo, it reported this error
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/780767be-37f8-452e-b718-f3c13c76d172">

Will you fix it or not maintenance this demo anymore?

**Comment by rohitgandikota** [comment]
Hi! The demo has a sleep time limit. It automatically closes after some inactivity period. I just restarted it again, hopefully you can catch it on time
