### ISSUE TITLE
Long training time?

### ISSUE THREAD

**Issue by quixot1c** [rohitgandikota/sliders#12]
Compared to training a LoRA via for example kohya scripts it takes a great deal longer to train a slider LoRA. Considering that the results are not always that great, because concepts got confused and retraining is needed with additional --attributes, would it be possible to get an idea of whether the training is going anywhere so we can adjust earlier or abort entirely?

Or could training speeds perhaps be increased somehow? Maybe LCM would be an option as it seems actual images are created during training, which is a lot faster with LCM.

**Comment by rohitgandikota** [comment]
Couple of options - 
1. Currently for text-based training - we are loading tensors to gpu only when needed. If there is enough GPU memory, I believe one can bypass the switching to just load all tensors directly to gpu device. 
2. Implementing xformers for sliders. This is an open task that we will be working on in the coming days. 
3. For testing intermediate results, in config file there is an option for save intermediate results `per_steps: 500`. You can store much earlier and test.

Given our base code is based on kohya script - we should be able to reduce the time a bit (my hunch - with xformers and accelerator). But we do note that our training has some additional steps compared to traditional training. It is bound to be slightly slower than the traditional lora training.

**Comment by rohitgandikota** [comment]
I also updated the scripts to streamline computation and reduce the device switching. In my end, I am seeing improvements.
