### ISSUE TITLE
How to compare image dataset (before/after edit for desired concept)?

### ISSUE THREAD

**Issue by XiaominLi1997** [rohitgandikota/sliders#13]
hello, thx for your nice work,

I wanna know how do you compare image dataset (before/after edit for desired concept)? Could you please provide some examples?

**Comment by rohitgandikota** [comment]
This is a before image:
![image](https://github.com/rohitgandikota/sliders/assets/17539718/1e50c11f-6619-45b2-86a2-c092e2333da9)

This is the corresponding after image:
![image](https://github.com/rohitgandikota/sliders/assets/17539718/b8cd945e-dcd3-4941-b3f0-a7cea6d1e36c)

I simply used some generated images of people. Used an online image editing tool, edited the eyebrow shape and saved the images with same name in a different folder. The training script is provided in README.md in the repo

**Comment by XiaominLi1997** [comment]
Thanks. According to readme, if I wanna learn a slider for eyebrows, I should prepare 4-6 pairs, no matter male or female, old or young?
![image](https://github.com/rohitgandikota/sliders/assets/25433111/6aca6a7a-1c4a-4018-9ce1-448fdbcef62d)

**Comment by rohitgandikota** [comment]
Yes, our training data had 6 images with 4 male and 2 female (not intentional). But it generalized pretty well.

**Comment by rohitgandikota** [comment]
Closing the issue - please feel free to reopen if the issue still persists
