### ISSUE TITLE
Practicable to applying it to another lora model (when SDXL already has a lora adaptor attached)?

### ISSUE THREAD

**Issue by asrlhhh** [rohitgandikota/sliders#15]
Hello! I appreciate your excellent work. Before I delve into experimenting with the code, I'm interested in understanding the practicality of implementing a concept slider on an existing LoRa model. Specifically, I'm referring to a scenario where the SDXL model already has a LoRa adapter integrated. I've previously trained a LoRa model using the [diffusers LoRa training script](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py). Is it possible to utilize this as a secondary adapter for semantic control on top of my existing model?

**Comment by rohitgandikota** [comment]
Hey thank you! I am glad you enjoyed the work

Practically, it should be possible. We have not tested it from our end though. We are working on enabling sliders for custom models, but if you are comfortable with coding, you can easily load your lora model during training. I would suggest adding a load script in the training after initiating the models. 

Will keep you posted on the custom model training update we are working on.

**Comment by asrlhhh** [comment]
Thanks. Will try it out
