### ISSUE TITLE
question about your training code: where is 'network' variable being used for training?

### ISSUE THREAD

**Issue by asrlhhh** [rohitgandikota/sliders#16]
Hello, I'm currently delving into the training code to tailor it for my specific needs. However, I'm puzzled about the integration of the LoRA slider into the main UNet. I noticed that the LoRA adapter is established within the 'network' variable, yet it seems to be utilized solely as a context manager in this section of the code while the training process still calls original unet 

https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/train_lora_xl.py#L205C1-L227C18

Is it some complex Python syntax that I'm not yet familiar with?

**Comment by rohitgandikota** [comment]
It is in `lora.py`. We wrote it such that during training, we easily load and unload the Loras. If you see LoRANetwork function in `lora.py`, you will see that the context manager simply turns the scale to 0 when exited.

**Comment by asrlhhh** [comment]
Thank you for your response. I've looked through the lora.py file and noticed the enter and exit functions. My confusion lies in the usage of `self.unet_loras`. After its declaration, I don't see it being actively used. The enter function modifies parameters within unet_loras, but it's not clear to me how unet_loras is involved in the `train_util.diffusion_xl()` process. Initially, I thought there was an in-place modification of the unet passed into the class constructor. However, I noticed that at the end of the init function, the unet object is deleted. Could you clarify how unet_loras is being called during training?

**Comment by rohitgandikota** [comment]
The `LoRANetwork` class method stores the lora modules. In the method we delete unet, but that does not impact the actual UNet we load in the training. We are just making the lora network class light. the `unet_loras` object is being used to collect the layers where we wish to add Loras to. We do not use it in training. It is just a helper variable in the class to create Loras.

**Comment by asrlhhh** [comment]
I want to clarify my confusion. In the training script, it seems that the `unet `object is consistently the original one from `UNet2DConditionModel`. In the `LoRAModule `and `LoRANetwork `classes, the intention appears to be modifying specific layers and the forward functions of `unet`, but this modification **doesn't seem to propagate back to** the `unet` except the `with ` statement. So my question is if the with statement is doing something else than setting up the multiplier value to share information with `unet`. 

Additionally, during inference, the network also loads its weights and interacts with `unet `solely via the `with `statement, so I guess this with statement has something pivotal here? I have to understand how it works before making edit on the codes.

`                with network:
                    noise_pred = unet(
                        latent_model_input,
                        t,
                        encoder_hidden_states=prompt_embeds,
                        cross_attention_kwargs=cross_attention_kwargs,
                        added_cond_kwargs=added_cond_kwargs,
                        return_dict=False,
                    )[0]`

**Comment by rohitgandikota** [comment]
This is from lora.py - as you can see the context entry is based on setting multiplier to non-zero scale and exiting will just set the scale to 0. Since we are loading Loras, those are just additional layers we load on top of pretrained unet. So in practice - `W_new = W_old + alpha * W_lora`. When `LoRANetwork` is called, new lora modules are created and kept on top of UNET. When you do `with network`, the Loras are activated and added to the pretrained model.  
```
def __enter__(self):
        for lora in self.unet_loras:
            lora.multiplier = 1.0 * self.lora_scale

    def __exit__(self, exc_type, exc_value, tb):
        for lora in self.unet_loras:
            lora.multiplier = 0
```

**Comment by asrlhhh** [comment]
Thanks. Actually this [single line](https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/lora.py#L105) is what I am looking for, not the enter and exit functions. Without this line, I wouldn't know how the lora adapter is attached to the old unet during training.

`self.org_module.forward = self.forward`
