### ISSUE TITLE
Unused code?

### ISSUE THREAD

**Issue by quixot1c** [rohitgandikota/sliders#18]
https://github.com/rohitgandikota/sliders/blob/4a0ac3ebed727fd0d11da3d2da70aa38077a0a61/trainscripts/textsliders/train_lora.py#L230C19-L230C19

The variable `orig_target_latents` does not seem to be used further in the code. It is also not present in `train_lora_xl.py`. Can the code block from 230-241 be removed?

**Comment by rohitgandikota** [comment]
yes! Thanks for catching it. Fixed it!
