### ISSUE TITLE
Support additional image types & handle resizing more gracefully

### ISSUE THREAD

**Issue by ThereforeGames** [rohitgandikota/sliders#19]
First, thank you for publishing your amazing work! My first impression of Textual Concepts training was very good. I'm attempting to train a Visual Concept now, but ran into a couple issues:

- The `train_lora-scale.py` script is hardcoded to use `.png` files (line 216); it should be trivial to extend support for other common filetypes such as `.jpg` and maybe `.webp`.
- The script also forces images to resize to 1024x1024. I'm guessing for SD 1.5 this should be 512x512, no? Also would be interesting if the trainer could support aspect ratio bucketing in the future. 🤔

Thanks!

**EDIT:** Hmm, I'm a little confused as to why the `train_lora-scale-xl` script resizes inputs to 512x512 while the `train_lora-scale` script uses 1024x1024. Isn't this backwards?

**Comment by rohitgandikota** [comment]
Thanks for the kind words and catching these! 

Made some of the changes:
1. we noticed that for SDXL resizing the images to 512 had a much better training performance. Do not have a strong intuition why. The SD training size was a bug - fixed it to 256. 
2. also added support to other image types.

**Comment by quixot1c** [comment]
Resizing to 256 has helped a lot in the training speed lol :D

**Comment by euminds** [comment]
> First, thank you for publishing your amazing work! My first impression of Textual Concepts training was very good. I'm attempting to train a Visual Concept now, but ran into a couple issues:
> 
> * The `train_lora-scale.py` script is hardcoded to use `.png` files (line 216); it should be trivial to extend support for other common filetypes such as `.jpg` and maybe `.webp`.
> * The script also forces images to resize to 1024x1024. I'm guessing for SD 1.5 this should be 512x512, no? Also would be interesting if the trainer could support aspect ratio bucketing in the future. 🤔
> 
> Thanks!
> 
> **EDIT:** Hmm, I'm a little confused as to why the `train_lora-scale-xl` script resizes inputs to 512x512 while the `train_lora-scale` script uses 1024x1024. Isn't this backwards?

What are the datasets required for Visual Concept training, and can you provide download links?

**Comment by rohitgandikota** [comment]
I would suggest reaching out to the amazing @Ostris - https://github.com/ostris/ai-toolkit 

He's the one we got our datasets from!

**Comment by rohitgandikota** [comment]
@euminds - here is our eyebrows dataset 
[eyebrows_data.zip](https://github.com/rohitgandikota/sliders/files/13496177/eyebrows_data.zip)
