### ISSUE TITLE
Crash when using `euler_a` sampler

### ISSUE THREAD

**Issue by ThereforeGames** [rohitgandikota/sliders#20]
Hi,

The training script does not run if you change the config `train.noise_scheduler` to `euler_a`:

```
  File "T:\code\python\sliders\trainscripts\textsliders\train_lora.py", line 433, in <module>
    main(args)
  File "T:\code\python\sliders\trainscripts\textsliders\train_lora.py", line 378, in main
    train(config=config, prompts=prompts, device=device)
  File "T:\code\python\sliders\trainscripts\textsliders\train_lora.py", line 189, in train
    latents = train_util.get_initial_latents(
  File "T:\code\python\sliders\trainscripts\textsliders\train_util.py", line 55, in get_initial_latents
    latents = noise * scheduler.init_noise_sigma
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Press any key to continue . . .
```

Updating `get_initial_latents()` in `train_util.py` as shown appears to fix it, although I'm not sure if I broke DDIM or something else in the process:

```
def get_initial_latents(
    scheduler: SchedulerMixin,
    n_imgs: int,
    height: int,
    width: int,
    n_prompts: int,
    generator=None,
) -> torch.Tensor:
    noise = get_random_noise(n_imgs, height, width, generator=generator).repeat(
        n_prompts, 1, 1, 1
    ).to("cuda")

    init_noise_sigma = torch.tensor(scheduler.init_noise_sigma).to("cuda")
    latents = noise * init_noise_sigma

    return latents
```

**Comment by quixot1c** [comment]
I ran into this as well, but tried to do it with the imagesliders per your suggestion and there it works fine. Maybe see how it is implemented there?

**Comment by rohitgandikota** [comment]
@quixot1c , imagesliders does not use the scheduler since we are working on real images (single step noising). 

@ThereforeGames, I don't think it broke the scheduler. It has something to do with how `Euler_a` sampler method handles devices? So from the error, I see that when you changed the scheduler to `Euler_a`, some of the torch variables are on CPU instead of GPU. I think the solution you came up with works!

**Comment by rohitgandikota** [comment]
Closing this issue. feel free to reopen if the issue persists.
