### ISSUE TITLE
Notebook not found

### ISSUE THREAD

**Issue by jacobmarks** [rohitgandikota/sliders#21]
When I click on the colab notebook button, the colab server gives the following, even after authenticating with GH:

<img width="1108" alt="Screenshot 2023-11-24 at 1 31 51 PM" src="https://github.com/rohitgandikota/sliders/assets/12500356/69386bdc-950e-4359-a12b-b467b26a17b9">

**Comment by rohitgandikota** [comment]
Oops. Fixed it now!
