### ISSUE TITLE
Is it possible to do this with img2img? 

### ISSUE THREAD

**Issue by kilimchoi** [rohitgandikota/sliders#24]
I was wondering if img2img could also work with this given the text prompt.

**Comment by rohitgandikota** [comment]
We tried some text-based image editing and provided the entire analysis in our paper. We are going to release a new version of arxiv soon with additional details. But did not particularly try the img2img pipeline. 

However, from our analysis we found that the text based modifications tend to introduce undesired interference with other concepts.

**Comment by kilimchoi** [comment]
Would be great if you could also add img2img pipeline to colab so we can experiment with it.

**Comment by rohitgandikota** [comment]
would love to try, currently we are looking into some additional features. will get to it after that. meantime, if you figure it out, feel free to create a pull request!

Thanks again for the heads

**Comment by rohitgandikota** [comment]
huh, I think there are some really cool pre-existing pipelines for image editing using img2img. Would recommend looking into it. I am not sure of specific repositories, but I am sure I came across a few

**Comment by kilimchoi** [comment]
It seems that i need to modify the _call function but I've been unable to get it to work with the existing StableDiffusionXLImg2ImgPipeline. I basically replaced the third cell in the colab with this, https://pastebin.com/sdqgbDWw
and replaced images call in the last cell with `images = pipe(prompt, image=init_image,num_images_per_prompt=1, num_inference_steps=50, generator=generator, network=network, start_noise=start_noise, scale=scale, unet=unet).images[0]`

**Comment by mofos** [comment]
I kinda works in ComfyUI, haven't Throughly Tested it though, using  eyesize.pt, -2 strength 
![img2img](https://github.com/rohitgandikota/sliders/assets/44880207/ad15420d-3d19-43c6-9728-c4b22a5ffc91)
you can load this work flow
[eyesize_Img2Img.json](https://github.com/rohitgandikota/sliders/files/13465481/eyesize_Img2Img.json)

**Comment by rohitgandikota** [comment]
@mofos Thank you!

**Comment by kilimchoi** [comment]
I don't think this is a right implementation. Txt2img should work but doesn't for me.

**Comment by leonardodora** [comment]
null-text inversion is a really good way to invert the real images into lantent codes.

**Comment by rohitgandikota** [comment]
yes! Good catch! We are working on the demo for real image editing. Check out our new appendix with info about real image editing: https://arxiv.org/pdf/2311.12092.pdf

**Comment by leonardodora** [comment]
> yes! Good catch! We are working on the demo for real image editing. Check out our new appendix with info about real image editing: https://arxiv.org/pdf/2311.12092.pdf

wow! so cool! would you realease the related codes recently?
Another question, do you think  it is difficult to edit hair length?
eg.![image](https://github.com/rohitgandikota/sliders/assets/13816743/85cba163-663f-4064-8c5f-84141a605c2c)

**Comment by rohitgandikota** [comment]
Yes! we will release it very soon! 


For hair length - I would suggest use `start_noise=850` or `900` it might help.

**Comment by leonardodora** [comment]
> Yes! we will release it very soon!
> 
> For hair length - I would suggest use `start_noise=850` or `900` it might help.

thanks a lot! I will try! you are so nice~

**Comment by leonardodora** [comment]
> The image editing demo with concept sliders is out! https://github.com/rohitgandikota/sliders/blob/main/demo_image_editing.ipynb

Amazing! Thanks for your work!
