### ISSUE TITLE
Question about the prompts file for text sliders

### ISSUE THREAD

**Issue by hkunzhe** [rohitgandikota/sliders#28]
To train the age text slider, is the [prompt.yaml](https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/data/prompts.yaml) with `--attributes=""` 
```
- target: "male person" # what word for erasing the positive concept from
  positive: "male person, very old" # concept to erase
  unconditional: "male person, very young" # word to take the difference from the positive concept
  neutral: "male person" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: "female person" # what word for erasing the positive concept from
  positive: "female person, very old" # concept to erase
  unconditional: "female person, very young" # word to take the difference from the positive concept
  neutral: "female person" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
```
equivalent to the following prompt with `--attributes="male, female"` ?
```
 - target: "person" # what word for erasing the positive concept from
  positive: "person, very old" # concept to erase
  unconditional: "person, very young" # word to take the difference from the positive concept
  neutral: "person" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
```

BTW, it seems that erasing/erase should be enhancing/enhance in the [prompt.yaml](https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/data/prompts.yaml).

**Comment by rohitgandikota** [comment]
Yes, but if you use the 1st option - then you can use attributes 'white, black, asian, hispanic, Indian,....' as ``--attributes` to preserve both gender and race directions

**Comment by hkunzhe** [comment]
@rohitgandikota, I got it! BTW, Would you kindly share the configuration files for the pre-trained models (especially image sliders) in https://sliders.baulab.info/weights/xl_sliders/?

**Comment by rohitgandikota** [comment]
Yes, for visual concept sliders (image based training), we don't use any prompts! 

So the default `config-xl.yaml` in the imagesliders folder is the one we used

**Comment by hkunzhe** [comment]
@rohitgandikota, I'm referring to the prompt files and image pairs corresponding to the pre-trained models. Sorry for the confusion.

**Comment by rohitgandikota** [comment]
prompts for the text sliders are here:  https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/data/prompts-xl.yaml

prompts for all the visual sliders are empty prompts:
https://github.com/rohitgandikota/sliders/blob/main/trainscripts/imagesliders/data/prompts-xl.yaml


Eyebrows data - 
[eyebrows_data.zip](https://github.com/rohitgandikota/sliders/files/13496168/eyebrows_data.zip)

**Comment by rfan-debug** [comment]
@rohitgandikota Thank you for the eyebrow dataset! How did you prepare it? Through photoshop or there is a script to generate it?

**Comment by rohitgandikota** [comment]
We generated the pairs using photoshop (a free online version) 

For example, in the case of eyesize, I would do the following:

1. First, collect 3-7 real images of people in close up poses
2. Using photoshop, I would first try to make the eyes slightly big - store these images in a folder names `high` 
3. I will repeat this process and make the eyes even bigger - store these new images in a folder named `veryhigh`
4. Next for negative pairs, do the photoshop edit to shrink the eyes slightly and store in `low`
5. shrink the eyes even further and store in `verylow`

you can do these variations at different levels, here I show 4 - people have done 10 too (but 4 in my opinion is good enough)
