### ISSUE TITLE
Datasets for the trained models

### ISSUE THREAD

**Issue by kilimchoi** [rohitgandikota/sliders#31]
Will it be possible to share some of the images you used to train these models? 
Discovered that some models work well and some don't on some images. I'm wondering if it's due to the images that were used to train it or if diffusion model's trying to figure out the concept.

**Comment by rohitgandikota** [comment]
I shared one dataset here: https://github.com/rohitgandikota/sliders/issues/28#issuecomment-1831222859

If model is not capturing the concept in your dataset - you can manually push it further by utilizing the prompts. For example, by default, we are not using the prompts for imagesliders. But you can add prompts. 

For hypothetical data where you have made car wheels wooden. You can use the prompts -
`positive - wooden wheels`
`neutral - wheels`
`target - wheels`

**Comment by kilimchoi** [comment]
can you share the datasets for young to old?

**Comment by rohitgandikota** [comment]
That's a text-based slider. The prompts we used are in the `trainscripts/textsliders/data/prompts-xl.yaml`

**Comment by kilimchoi** [comment]
https://sliders.baulab.info/weights/sd14_sliders/chubby_sd14.pt <- you're saying this is a text slider? 
So it doesn't have to be image-based slider to edit images?

**Comment by rohitgandikota** [comment]
I think you are misunderstanding the text slider. It means that the slider is built using text descriptions. Any slider, either built from text or images, can be used to edit images. 

For better clarity, I would suggest reading our paper.

**Comment by kilimchoi** [comment]
Sorry still haven't had a chance to read the paper but would appreciate if you could share what benefit one would gain by training a visual concept slider over just using a text one. If this is detailed in the paper, feel free to say so. I will look for the answer in the paper.

**Comment by rohitgandikota** [comment]
Some concepts maybe not be described in text. And there are concepts that the models have hard time to comprehend. For instance, the qualitative examples we show for style gan transferred sliders are hard to build with text
