### ISSUE TITLE
Request to Share parameter used in training for Fix_hands.pt

### ISSUE THREAD

**Issue by mofos** [rohitgandikota/sliders#34]
Hi, I was particular interested in the Fix_hands.pt slider, but was getting mixed results with Juggernaut-xl, I have used the EyeSize.pt and it works well. was curious to see what kind of parameters were used if available for the shared LoRa files. Please direct me, if it's already been shared, Thanks!!!

**Comment by rohitgandikota** [comment]
Yes! The prompts we used are present here - https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/data/prompts-xl.yaml (in the very bottom). I would also suggest using the repair slider to see if that works better?
