### ISSUE TITLE
UnidentifiedImageError: cannot identify image file 'stock_photo_girl.jpg'

### ISSUE THREAD

**Issue by nextosai** [rohitgandikota/sliders#37]
Congrats for this great work. When running the demo_image_editing.ipynb colab, I get an error message 
UnidentifiedImageError: cannot identify image file 'stock_photo_girl.jpg'
Am I doing something wrong:
Thanks!

**Comment by rohitgandikota** [comment]
hey, looks like you need to run the notebook from cell number 2 - if you restarted your kernel after installing the required libraries, you will have to run `!cd sliders` again in your colab notebook. Which is taken care by cell number 2. 

If this is too confusing - you can simply replace the 'stock_photo_girl.jpg' with 'sliders/stock_photo_girl.jpg'

**Comment by xpeng** [comment]
> Congrats for this great work. When running the demo_image_editing.ipynb colab, I get an error message UnidentifiedImageError: cannot identify image file 'stock_photo_girl.jpg' Am I doing something wrong: Thanks!

maybe you can try png.

**Comment by rohitgandikota** [comment]
Oh no - it is jpg. The demo downloads this image from our servers 
![](https://sliders.baulab.info/sample_images/stock_photo_girl.jpg)

It is jpg format. the solution I provided should do the trick
