### ISSUE TITLE
Compare with LEDITS

### ISSUE THREAD

**Issue by sjYuxuan** [rohitgandikota/sliders#38]
It seems that the essence of your work is the same as LEDITS. Can you compare with them, please?

**Comment by rohitgandikota** [comment]
LEDITS is a great real image editing method, while the main focus of our paper was for smoothly controlling the image generation of the models. They might not fall under the same category for comparison. Thanks

**Comment by rohitgandikota** [comment]
That being said, we did compare against text-based image generation control, which could have similar performance to ledits. You can check out our paper for more details. (We label it as "composition" in our experiments)
