### ISSUE TITLE
chardet required

### ISSUE THREAD

**Issue by andreamoreto** [rohitgandikota/sliders#40]
Just to let you know that, using conda, I received this message :

`Traceback (most recent call last):
  File "C:\Users\AdminI9\anaconda3\envs\sliders\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'`

Fixed with 'pip install chardet'.

Eventually, chardet should be included on requirements.txt

eta: forgot to mention -> Windows10

**Comment by rohitgandikota** [comment]
looking like your `requests` library is outdated.

diffusers should have taken care of it. 

Thanks for sharing it here. Will be useful for future issues!
