### ISSUE TITLE
question about your Evaluate code: where is Visual Concept Sliders Evaluate code for Evaluating?

### ISSUE THREAD

**Issue by yytang25** [rohitgandikota/sliders#43]
Congrats for this great work. 
where is Visual Concept Sliders Evaluate code for Evaluating?
Thanks!

**Comment by rohitgandikota** [comment]
If you mean, code for generating images - it is same as text sliders. It is in `/evalscripts` folder

**Comment by yytang25** [comment]
> If you mean, code for generating images - it is same as text sliders. It is in `/evalscripts` folder

Sorry, I didn't explain it clearly before. What I meant was how to test on my own image data set after training imagesliders.

**Comment by rohitgandikota** [comment]
Yes, all the evaluation codes and notebooks provided are generic. They can help you with both text sliders and image sliders. 

For image editing - you can refer to this notebook https://github.com/rohitgandikota/sliders/blob/main/demo_image_editing.ipynb

**Comment by yytang25** [comment]
> Yes, all the evaluation codes and notebooks provided are generic. They can help you with both text sliders and image sliders.
> 
> For image editing - you can refer to this notebook https://github.com/rohitgandikota/sliders/blob/main/demo_image_editing.ipynb

Thank you for your timely reply. I will take a closer look when I get back. Best wishes.
