### ISSUE TITLE
Why performance of on dog is bad?

### ISSUE THREAD

**Issue by yxchng** [rohitgandikota/sliders#46]
I only edited prompt.yaml and train using the official command:

`python trainscripts/textsliders/train_lora.py --attributes 'male, female' --name 'ageslider' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config.yaml'`

prompt.yaml:
```
- target: "dog" # what word for erasing the positive concept from
  positive: "dog, very old" # concept to erase
  unconditional: "dog, very young" # word to take the difference from the positive concept
  neutral: "dog" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512 
  dynamic_resolution: false
  batch_size: 1
```

The result I got when running demo_image_editing.ipynb (only modifying scales to [-1, 0, 2, 4, 6, 8, 10]):

![output](https://github.com/rohitgandikota/sliders/assets/10518587/52f70452-8e92-4edd-a119-2099ac6bc930)

**Comment by rohitgandikota** [comment]
It could be for couple of reasons:
1. Maybe old dog and young dog are not the right tokens for the model to understand. You could try with "old dog" and "puppy"
2. During Inference, I would suggest to use larger values for `start_noise` - maybe 900 or even 950
3. If you want to try on XL - i would suggest to add more attributes like "golden retriever, poodle, Dalmatian" etc.

**Comment by rohitgandikota** [comment]
`start_noise` is a parameter you can setup during inference. So, there is nothing to do with training.  I would suggest looking at the demo notebook in our repo

Now, for training, some users found lower `lr`(learning rate) are better for some concepts. Next, I would suggest playing around with the rank. We found that usually rank 1 can do the trick. But it's something to play around with. Finally (but definitely not the least), I would suggest prompt engineering during training.

Hope that helps

**Comment by PotatoBananaApple** [comment]
> `start_noise` is a parameter you can setup during inference. So, there is nothing to do with training. I would suggest looking at the demo notebook in our repo
> 
> Now, for training, some users found lower `lr`(learning rate) are better for some concepts. Next, I would suggest playing around with the rank. We found that usually rank 1 can do the trick. But it's something to play around with. Finally (but definitely not the least), I would suggest prompt engineering during training.
> 
> Hope that helps

Thank you for answer! This i really nice tool. Tested the image slider and it seemed to work nicely. Noticed it darkens/adds contrast a bit too much, maybe need to play around more with the lr. 

I don't quite understand what you mean with _prompt engineering during training._?

**Comment by rohitgandikota** [comment]
By prompt engineering I mean - if some prompt is not working for example as the original issue states `old dog` -> `young dog` does not seem to work. You could always rewrite the prompts as `old dog` -> `young puppy`. There are several ways to play around with the prompts.

**Comment by rohitgandikota** [comment]
closing the issue - feel free to reopen if issue persists
