### ISSUE TITLE
Visual Concept Sliders training is not working properly.

### ISSUE THREAD

**Issue by toyxyz** [rohitgandikota/sliders#47]
I am following the readme and trying to train the visual concept slider(eye). 

But when I try to generate an image after the training is done, it generates a mess. Am I missing something?

![image](https://github.com/rohitgandikota/sliders/assets/8006000/ea9ab4c3-4215-47d5-82ef-9bfd33c89513)

Here is the pair image I prepared.

python trainscripts/imagesliders/train_lora-scale.py --name "eyeslider" --rank 4 --alpha 1 --config_file "trainscripts/imagesliders/data/config_2.yaml" --folder_main "datasets/eyesize/" --folders "bigsize, smallsize" --scales "1, -1"

bigsize
![image](https://github.com/rohitgandikota/sliders/assets/8006000/8fcf493e-a5e4-431c-80bc-48a835a39bd9)
smallsize
![image](https://github.com/rohitgandikota/sliders/assets/8006000/4eb3e772-345a-4186-bb46-e7139b7c00e6)
![image](https://github.com/rohitgandikota/sliders/assets/8006000/82003c25-0a12-42ed-a6c5-47f607c49060)
![image](https://github.com/rohitgandikota/sliders/assets/8006000/ae040f38-3c2b-40af-b80c-faf89d36981e)

**Comment by toyxyz** [comment]
I found the cause: LR was too high. By lowering it from 0.0002 to 0.00001, I was able to transform just the parts I wanted without distorting the overall style.  I was wondering if you could share the settings you used for the training, such as LR and optimizer? Thanks! 

https://github.com/rohitgandikota/sliders/assets/8006000/46320438-4444-4cf0-80cb-d2048fb7647d

**Comment by rohitgandikota** [comment]
Oh awesome! We used the default parameters as provided in the repository. Glad you could get your custom dataset working! Closing this issue since it is resolved! 

The slider looks amazing!!!
