### ISSUE TITLE
error: the following arguments are required: --alpha

### ISSUE THREAD

**Issue by DarkAlchy** [rohitgandikota/sliders#48]
All of this is set in the config.yaml, and should not be needed on the command line.

![image](https://github.com/rohitgandikota/sliders/assets/10561690/0afef263-2dea-4bb5-9b57-3ad95953801c)

There is why it is a typo and that True change to False.

**Comment by DarkAlchy** [comment]
30m to train one of these on a 4090 for 1000 steps is normal?

temp_alphaNone_rank4_noxattn_last.pt (all of them say alpha0).

filename is funky or did it not take the alpha set in the config?

**Comment by rohitgandikota** [comment]
we made it as a command line argument for analysis convenience in our paper. If you have some values that are constant and fixed during training, I would suggest setting their default values here 
```
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config_file",
        required=True,
        help="Config file for training.",
    )
    # config_file 'data/config.yaml'
    parser.add_argument(
        "--alpha",
        type=float,
        required=False,
        help="LoRA weight.",
       default = 1.0 ###### LIKE THIS HERE
    )
    # --alpha 1.0
    parser.add_argument(
        "--rank",
        type=int,
        required=False,
        help="Rank of LoRA.",
       default = 4
    )
``` 

Hope that is useful.

**Comment by DarkAlchy** [comment]
Not meaning to be disrespectful but setting anything outside the .yaml is a stupid idea that nullifies the yaml.  My way allows it to be done the proper way.

Thank you.
