### ISSUE TITLE
Can I use lora sliders with peft?

### ISSUE THREAD

**Issue by zzmicer** [rohitgandikota/sliders#49]
Hi, thanks for your job, looks promising!

I've come through your inference code, you are using custom LoRANetwork class, however diffusion lib already has all necessary functions for loading and inferencing with lora(including PEFT integration).

Can I load loras, trained by your train script, directly via diffusers/peft api, like `pipe.load_lora_weights`?

Thanks!

**Comment by rohitgandikota** [comment]
Sure! The reason we adopted the LoRANetwork class from Kohya implementation was to allow Loras on custom layers. I believe the diffusers implementation does not allow for self attentions only lora loading. But if you wish to load lora on all the layers or all the attention layers, the  `pipe.load_lora_weights` should do the trick. 

Also - the training code might have to be changed

**Comment by zzmicer** [comment]
It seems like, you're learning not only attention layers but also Conv and Linear layers. But diffusers load_lora_weights function loads only cross-attentions. 

Please correct me if I'm wrong 🙃

**Comment by rohitgandikota** [comment]
Good question, I was under the impression that load_lora_weights did both cross and self attentions. Where as we also do conv layers. But more importantly, our method allows us to specify the layers we want to load Loras on. For example just cross attentions or just self attentions

But you are absolutely right about the conv layer Loras which might not be supported on `load_lora_weights` method
