### ISSUE TITLE
Cannot import lora

### ISSUE THREAD

**Issue by mandelapatrick** [rohitgandikota/sliders#5]
from lora import LoRANetwork, DEFAULT_TARGET_REPLACE, UNET_TARGET_REPLACE_MODULE_CONV

Where is the lora file? I cannot seem to import.

**Comment by lkmdhertg** [comment]
Same for me. There is something here: https://github.com/bmaltais/kohya_ss/blob/master/networks/lora.py
But except for LoRANetwork the other import (DEFAULT_TARGET_REPLACE ...) are not included there

**Comment by rohitgandikota** [comment]
The lora.py are in `train-scripts/textsliders`

**Comment by rohitgandikota** [comment]
The new update should resolve this issue. Thanks
