### ISSUE TITLE
I have a question about Visual Concept Sliders!

### ISSUE THREAD

**Issue by toyxyz** [rohitgandikota/sliders#50]
Hi! I'm trying to train a slider to remove the background from an image and replace it with white.

But the visual slider didn't work as I expected. I changed Lr and rank but didn't get the desired result. The result is not stable compared to the text slider. 

On the right is a green screen Lora that I previously created using the copier Lora technique. What would I need to modify to get a similar result with the visual concept slider? (https://note.com/kohya_ss/n/nb258da07236f)

![image](https://github.com/rohitgandikota/sliders/assets/8006000/e01dc0a5-991b-4ed6-b56c-a1b1c8d83ea3)

Below is the image pair I prepared.
![image](https://github.com/rohitgandikota/sliders/assets/8006000/315c4b95-5667-4c2d-8552-f3ae9ac5af47)

**Comment by rohitgandikota** [comment]
Very interesting - I see text slider works decent compared to visual slider here. So my hunch is:
1. You could use prompts for visual sliders (same prompts you used for visual sliders). Especially - for positive "" and for neutral "white background"  
2. maybe you can try overfitting the slider (large training steps)

This is completely different suggestion to sliders. You could also look into foreground-background segmentation with diffusion models. I believe there are works that show these segmentations using linear probes on top of intermediate activations. If you haven't explored this direction, it could be something to look into

**Comment by toyxyz** [comment]
Raising Lr to 0.001 and changing rank to 1 seems to work somewhat. 

![AnimateDiff_00709](https://github.com/rohitgandikota/sliders/assets/8006000/71341ca0-2e7f-4801-b3f7-271e41d782b6)

However, it still seems like the duplicator lora works a little better. 

![AnimateDiff_00710](https://github.com/rohitgandikota/sliders/assets/8006000/a23132d0-a92f-4703-9eba-473c9e9dea02)

**Comment by rohitgandikota** [comment]
Awesome, so that's definitely better than the last one. What is the start_noise you are using for generation? You could try out values - 600, 650, 700, 750, 800, 850, 900. I'm guessing this could help too

**Comment by rohitgandikota** [comment]
closing the issue. Please feel free to reopen if issues persist. Thanks!
