### ISSUE TITLE
how can i use repair slider in the demo_image_editing.ipynb

### ISSUE THREAD

**Issue by SlZeroth** [rohitgandikota/sliders#51]
I got this error 

 Error(s) in loading state_dict for LoRANetwork:
	Missing key(s) in state_dict: "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q.alpha", "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q.lora_down.weight", 

when I m trying to use repair.pt in the demo_image_editing.ipynb

**Comment by rohitgandikota** [comment]
Right - so repair slider is on SDXL and the demo_image_editing is on SD1.4 

You will not be able to use it directly from the pretrained sliders. You might have to build a repair slider for SD1.4 

The prompts used are provided in `trainscripts/textslider/data/prompts-xl.yaml` - you would have to use those for SD1.4 

Hope that helps.
