### ISSUE TITLE
atifacts when runing demo_image_editing

### ISSUE THREAD

**Issue by rainsoulsrx** [rohitgandikota/sliders#53]
hi, I run this demo , but got bad results as follows:
<img width="1641" alt="image" src="https://github.com/rohitgandikota/sliders/assets/24955512/c494495a-8e66-4b5b-a5fb-d1c23ea8ccef">
the inversion is good, but after editing, the result is bad
<img width="363" alt="image" src="https://github.com/rohitgandikota/sliders/assets/24955512/1514f0b2-22da-422e-958f-fa22846b27f8">

**Comment by rohitgandikota** [comment]
huh, I am not sure. could you try with different images? I would also play around with the prompts used during inversion. you can be more specific like "photo of a man with short hair, with white tank top" or you can try just "person". I am not really sure what would do the trick here. Because looks like the reconstruction is not as good (given one of the slider images with scale=0 also has artifact)

**Comment by rainsoulsrx** [comment]
> huh, I am not sure. could you try with different images? I would also play around with the prompts used during inversion. you can be more specific like "photo of a man with short hair, with white tank top" or you can try just "person". I am not really sure what would do the trick here. Because looks like the reconstruction is not as good (given one of the slider images with scale=0 also has artifact)

yes, I try with this image, the result is ok, but I change the prompt with the problematic image, the result is still bad:
<img width="1282" alt="企业微信截图_f5a81cef-2fae-40fd-adaf-411161465882" src="https://github.com/rohitgandikota/sliders/assets/24955512/40b93547-627c-47bc-a0ca-6b49d0cf409d">
<img width="1285" alt="image" src="https://github.com/rohitgandikota/sliders/assets/24955512/186e910f-2e5c-4324-9002-5a72901a4bef">

**Comment by rainsoulsrx** [comment]
And I test Xl slider inference with eyebrow lora, it influence other area besides eyebrow:
<img width="1131" alt="image" src="https://github.com/rohitgandikota/sliders/assets/24955512/55851e96-6a73-4c50-8ffa-79f58237b2d6">
<img width="1134" alt="image" src="https://github.com/rohitgandikota/sliders/assets/24955512/2f844a75-4630-4f36-97ef-8c6f7378eb32">

**Comment by rohitgandikota** [comment]
I see, this looks to be related to null inversion. Clearly the null inversion can invert the top image very good, but the bottom image without slider is still not properly reconstructed. 

To reduce the effect on other aspects in image - you can reduce the `start_noise` parameter during inference. 

Closing this issue. please feel free to reopen if the issue persists

**Comment by rainsoulsrx** [comment]
> And I test Xl slider inference with eyebrow lora, it influence other area besides eyebrow: <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/24955512/292734761-55851e96-6a73-4c50-8ffa-79f58237b2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzgyNDAsIm5iZiI6MTcwMzU3Nzk0MCwicGF0aCI6Ii8yNDk1NTUxMi8yOTI3MzQ3NjEtNTU4NTFlOTYtNmE3My00YzUwLThmZmEtNzlmNTgyMzdiMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNGU5NGJhNjI0YTBjNTEwYWU4MDk4NDg5ZGU4MGQwY2Y5NjYyNWY5YmUwMmM3MmEyOGQwNTJjY2I5YzQwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dDZNrDCMekSImNhCfNscn_yjALfA35n3qY5VcvoRrVE"> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/24955512/292734884-2f844a75-4630-4f36-97ef-8c6f7378eb32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzgyNDAsIm5iZiI6MTcwMzU3Nzk0MCwicGF0aCI6Ii8yNDk1NTUxMi8yOTI3MzQ4ODQtMmY4NDRhNzUtNDYzMC00ZjM2LTk3ZWYtOGM2ZjczNzhlYjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzMxNDM4YmQzZGM5NDVkY2MzMGFhNDFmNDRhMDJhNWYyYWY4YjYzN2ZkZjIwMjA5ZGM4NjBmOTRjZGQxYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PcNVIv8QCArzum8WKyeHwvqv8xeOOEPF3wS_RADeeF8">

this is not about real image edit, when the scale is large, it seems will affect other attribute， when scale small, the effect is not obvious.
