### ISSUE TITLE
optimizer support?

### ISSUE THREAD

**Issue by Zuco-M** [rohitgandikota/sliders#57]
Which kind of optimizer does this script support?

**Comment by rohitgandikota** [comment]
You can find the supported optimizers here https://github.com/rohitgandikota/sliders/blob/6f0401ba75bfd659b3d2dfff5bfbe750714baaa5/trainscripts/textsliders/train_util.py#L336C1-L336C1

**Comment by rohitgandikota** [comment]
Closing the issue
