### ISSUE TITLE
Is it possible to train with checkpoints?

### ISSUE THREAD

**Issue by audwns1gh** [rohitgandikota/sliders#6]
The config file says I can use ckpt or safetensors, but when I tried gsdf/Counterfeit-V3.0 as a test, I get an error. Reading the error, it looks like it won't train unless it's a diffuser.

**OSError: gsdf/Counterfeit-V3.0 does not appear to have a file named text_encoder/config.json. Checkout 'https://huggingface.co/gsdf/Counterfeit-V3.0/main' for available files.**

I was also wondering if it is possible to train with a locale model?

**Comment by rohitgandikota** [comment]
Hey, thanks for letting us know! We will look into this and get back to you

**Comment by audwns1gh** [comment]
Thank you, I'll try it soon!

**Comment by andreamoreto** [comment]
**SDXL**, using the standard  'sd_xl_base_1.0.safetensors' or any other safetensor file, I receive this error :

`(sliders) H:\sliders>python trainscripts/imagesliders/train_lora-scale-xl.py --name "Pslider2XL" --rank 4 --alpha 1 --config_file "H:\sliders\trainscripts\imagesliders\data\config-xl.yaml" --folder_main "H:\sliders" --folders "bigsize,smallsize" --scales "1,-1"
[{'target': 'penguin', 'positive': 'large penguin', 'unconditional': 'penguin', 'neutral': 'penguin', 'action': 'enhance', 'guidance_scale': 4, 'resolution': 512, 'dynamic_resolution': False, 'batch_size': 1}, {'target': 'penguin', 'positive': 'small penguin', 'unconditional': 'penguin', 'neutral': 'penguin', 'action': 'enhance', 'guidance_scale': -4, 'resolution': 512, 'dynamic_resolution': False, 'batch_size': 1}]
[{'target': 'penguin', 'positive': 'large penguin', 'unconditional': 'penguin', 'neutral': 'penguin', 'action': 'enhance', 'guidance_scale': 4, 'resolution': 512, 'dynamic_resolution': False, 'batch_size': 1}, {'target': 'penguin', 'positive': 'small penguin', 'unconditional': 'penguin', 'neutral': 'penguin', 'action': 'enhance', 'guidance_scale': -4, 'resolution': 512, 'dynamic_resolution': False, 'batch_size': 1}]
2 2
['bigsize', 'smallsize'] [1, -1]
Traceback (most recent call last):
  File "H:\sliders\trainscripts\imagesliders\train_lora-scale-xl.py", line 548, in <module>
    main(args)
  File "H:\sliders\trainscripts\imagesliders\train_lora-scale-xl.py", line 466, in main
    train(config=config, prompts=prompts, device=device, folder_main = args.folder_main, folders = folders, scales = scales)
  File "H:\sliders\trainscripts\imagesliders\train_lora-scale-xl.py", line 80, in train
    ) = model_util.load_models_xl(
  File "H:\sliders\trainscripts\imagesliders\model_util.py", line 232, in load_models_xl
    return tokenizers, text_encoders, unet, scheduler, vae
UnboundLocalError: local variable 'vae' referenced before assignment`

Windows10, I'm using the follow line in config-xl file :
`  name_or_path: "H:\\SD_Tests\\checkpoints\\SDXL\\sd_xl_base_1.0.safetensors" # you can also use .ckpt or .safetensors models `

using the hugginface repository address works flawlessly, after the model's diffusers download.

**Comment by rohitgandikota** [comment]
Hi @andreamoreto - thanks for the patience. This should be fixed now. Let me know if it still persists. I'm happy to look into it. The current fix is done in `model_utils.py`.

Closing this issue - please feel free to reopen if the issue still persists
