### ISSUE TITLE
Is the method based on Lora

### ISSUE THREAD

**Issue by Open-Debin** [rohitgandikota/sliders#61]
Dear Author,

Thank you very much for sharing this code, but I have a question that from your codes I think it is not based on Lora.
Please see the following link to your code.
https://github.com/rohitgandikota/sliders/blob/4560f5f01241e0ba3c289d1e4e1ba1bf1a7c927f/trainscripts/textsliders/lora.py#L111

Your core code is this: 
`self.org_forward(x) + self.lora_up(self.lora_down(x)) * self.multiplier * self.scale`

This code is merging the two outputs from two model weights, but lora should only have one output because lora only have one model weight which is merged from two model weights.
<img width="206" alt="image" src="https://github.com/rohitgandikota/sliders/assets/52323137/3098d273-b22c-43b9-a7a6-1e8f0c08898a">

Thank you for your attention for this question, I would be very much thanking you for your feedback.

**Comment by rohitgandikota** [comment]
Yes - our sliders are LoRA adaptors. But are trained differently compared to standard LoRAs.

As you said - LoRA has one output that merges with original weights. It is correct! 
So in our code: `self.org_forward(x) + self.lora_up(self.lora_down(x)) * self.multiplier * self.scale`

* `self.org_forward` is the output from original weights
* `self.lora_up(self.lora_down(x))` is the lora output 

the `lora_up` and `lora_down` are the modules of a single lora as seen here.
![image](https://github.com/rohitgandikota/sliders/assets/17539718/6f624c69-c64a-48db-82a1-352324b71d8a)

Please refer to the LoRA paper for more information (https://arxiv.org/abs/2106.09685)
