### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by yuyifan1991** [rohitgandikota/sliders#63]
After I trained my datasets, I got some .pt model file, and how to produce the pictures by script file in Linux?

**Comment by rohitgandikota** [comment]
To evaluate your trained models, you can use the notebook `XL-sliders-inference.ipynb`

**Comment by rohitgandikota** [comment]
If you need to use a script file - refer to `eval-scripts/generate_images_xl.py` 

The prompts file has to be a csv with headers prompt, evaluation_seed, case_number. You can use this as reference https://github.com/rohitgandikota/sliders/blob/main/prompts/prompts-car.csv
