### ISSUE TITLE
BatchTraining

### ISSUE THREAD

**Issue by Open-Debin** [rohitgandikota/sliders#66]
Dear Rohit Gandikota,

I appreciate you sharing your code. I've observed that your model is trained on individual prompt pairs (target, neutral, positive, unconditional) for each iteration, rather than utilizing batch data. Training on batches is known to enhance training stability and facilitate smoother convergence.

I'm curious to understand why your model is not trained on batch data. Additionally, could you provide guidance on how I might modify the code to enable batch training?

Thank you for your attention, and I extend my best wishes.

**Comment by rohitgandikota** [comment]
Hi @Open-Debin, I am glad you are enjoying the work! 

We did implement batch training for individual prompts, you can refer to the prompts_xl.yaml (https://github.com/rohitgandikota/sliders/blob/main/trainscripts/textsliders/data/prompts-xl.yaml) and reset the batch_size

However, this will allow batch training for individual prompt pairs. You can look into batch training across the prompt pairs by tweeting this line here:https://github.com/rohitgandikota/sliders/blob/4560f5f01241e0ba3c289d1e4e1ba1bf1a7c927f/trainscripts/textsliders/train_lora_xl.py#L170


hope this helps

**Comment by rohitgandikota** [comment]
Closing the issue - please free to reopen if the issue persists
