### ISSUE TITLE
prepare datasets

### ISSUE THREAD

**Issue by xlc-github** [rohitgandikota/sliders#68]
thanks for your awesome work,now I want to train a age-slider,but I don`t know how to prepare the training datasets.how to prepare the datasets

**Comment by rohitgandikota** [comment]
You can build a age-slider from prompts/text alone. The way we built our prompts are:
1. Use the trainscripts/textsliders/data/prompts-xl.yaml to set your prompts like this
```
- target: "male person" # what word for erasing the positive concept from
  positive: "male person, very old" # concept to erase
  unconditional: "male person, very young" # word to take the difference from the positive concept
  neutral: "male person" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: "female person" # what word for erasing the positive concept from
  positive: "female person, very old" # concept to erase
  unconditional: "female person, very young" # word to take the difference from the positive concept
  neutral: "female person" # starting point for conditioning the target
  action: "enhance" # erase or enhance
  guidance_scale: 4
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
```
This is already the default file, so you dont have to change anything. 

2. Then you can setup the config-xl.yaml in the same folder for more detailed tweeks in training. I suggest to leave it in default. 

3. Finally you can run the script: 
```
python trainscripts/textsliders/train_lora_xl.py --attributes 'white, black, asian, hispanic, indian' --name 'agesliderXL' --rank 4 --alpha 1 --config_file 'trainscripts/textsliders/data/config-xl.yaml'
```

This will train your slider. You can use the https://github.com/rohitgandikota/sliders/blob/main/XL-sliders-inference.ipynb notebook to test your sliders.

For detailed instructions to setup and run these scripts. Please refer to the readme here https://github.com/rohitgandikota/sliders/tree/main#setup

**Comment by rfan-debug** [comment]
@rohitgandikota Do you mind sharing how you prepare the visual slider's training data? I tried to take photos of the same object with slightly variations to create sliders, but the trained image slider tends to produce very vague outputs.

**Comment by rohitgandikota** [comment]
Here is an example dataset we shared - eyebrow dataset: https://github.com/rohitgandikota/sliders/issues/28#issuecomment-1831222859

The idea is that you need a pair of variations. For instance you need both small eyes (or normal eyes) and big eyes images. Both of them have to be very close. Please refer to the dataset I shared above. Hope it helps
