### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by navarisun1982** [rohitgandikota/sliders#69]
i have already xformers which is working with stable diffusion,

here is the error i got when i start training in poweshell

`WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.10)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[{'target': 'man', 'positive': 'man, eyes open', 'unconditional': 'man, eyes closed', 'neutral': 'man', 'action': 'enhance', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}, {'target': 'woman', 'positive': 'woman, eyes open', 'unconditional': 'woman, eyes closed', 'neutral': 'woman', 'action': 'erase', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}]
[{'target': 'man man', 'positive': 'man man, eyes open', 'unconditional': 'man man, eyes closed', 'neutral': 'man man', 'action': 'enhance', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}, {'target': 'woman man', 'positive': 'woman man, eyes open', 'unconditional': 'woman man, eyes closed', 'neutral': 'woman man', 'action': 'enhance', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}, {'target': 'man woman', 'positive': 'man woman, eyes open', 'unconditional': 'man woman, eyes closed', 'neutral': 'man woman', 'action': 'erase', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}, {'target': 'woman woman', 'positive': 'woman woman, eyes open', 'unconditional': 'woman woman, eyes closed', 'neutral': 'woman woman', 'action': 'erase', 'guidance_scale': 4, 'resolution': 1024, 'dynamic_resolution': False, 'batch_size': 2}]
2 4
[PromptSettings(target='man man', positive='man man, eyes open', unconditional='man man, eyes closed', neutral='man man', action='enhance', guidance_scale=4.0, resolution=1024, dynamic_resolution=False, batch_size=2, dynamic_crops=False), PromptSettings(target='woman man', positive='woman man, eyes open', unconditional='woman man, eyes closed', neutral='woman man', action='enhance', guidance_scale=4.0, resolution=1024, dynamic_resolution=False, batch_size=2, dynamic_crops=False), PromptSettings(target='man woman', positive='man woman, eyes open', unconditional='man woman, eyes closed', neutral='man woman', action='erase', guidance_scale=4.0, resolution=1024, dynamic_resolution=False, batch_size=2, dynamic_crops=False), PromptSettings(target='woman woman', positive='woman woman, eyes open', unconditional='woman woman, eyes closed', neutral='woman woman', action='erase', guidance_scale=4.0, resolution=1024, dynamic_resolution=False, batch_size=2, dynamic_crops=False)]
Traceback (most recent call last):
  File "D:\Lora Slider\sliders\trainscripts\textsliders\train_lora_xl.py", line 463, in <module>
    main(args)
  File "D:\Lora Slider\sliders\trainscripts\textsliders\train_lora_xl.py", line 411, in main
    train(config, prompts, device)
  File "D:\Lora Slider\sliders\trainscripts\textsliders\train_lora_xl.py", line 68, in train
    ) = model_util.load_models_xl(
  File "D:\Lora Slider\sliders\trainscripts\textsliders\model_util.py", line 223, in load_models_xl
    ) = load_diffusers_model_xl(pretrained_model_name_or_path, weight_dtype)
  File "D:\Lora Slider\sliders\trainscripts\textsliders\model_util.py", line 139, in load_diffusers_model_xl
    CLIPTokenizer.from_pretrained(
  File "C:\Users\Z840\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 1702, in from_pretrained
    raise ValueError(
ValueError: Calling CLIPTokenizer.from_pretrained() with the path to a single file or url is not supported for this tokenizer. Use a model identifier or the path to a directory instead.`

**Comment by Voidbord** [comment]
I'm not an expert but it seems you have wrong version of pytorch - you use cpu here not gpu. Do you have an nvidia gpu?

**Comment by navarisun1982** [comment]
> I'm not an expert but it seems you have wrong version of pytorch - you use cpu here not gpu. Do you have an nvidia gpu?

Yes, i have a p40 tesla, which works well with stable diffusion and comfyui

**Comment by Voidbord** [comment]
You can start with opening cmd, enter the venv (virtual environment) and type:
pip uninstall torch torchvision torchaudio
pip uninstall xformers
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Probably you don't have to reinstall python to version 3.10.11
