### ISSUE TITLE
Please make a pull request to Automatic1111 SD Web UI for support

### ISSUE THREAD

**Issue by FurkanGozukara** [rohitgandikota/sliders#7]
Majority of the Stable Diffusion community using that UI

That will be super uber helpful

**Comment by quixot1c** [comment]
It is not up to researchers to implement their code in an arbitrary UI of your choosing. This is up to the community, so the researchers can go on and invent even more awesome things.

**Comment by FurkanGozukara** [comment]
> It is not up to researchers to implement their code in an arbitrary UI of your choosing. This is up to the community, so the researchers can go on and invent even more awesome things.

I disagree

There are so many research that had been 0 times used because of exactly the reason you mentioned

**Comment by fgtm2023** [comment]
+2 :)

**Comment by rohitgandikota** [comment]
Hi folks, thanks for the interest in our work! Really appreciate it!

Some amazing folks are working on implementing concept sliders on AUTOMATIC111 and comfyUI. Will keep you posted.

**Comment by FurkanGozukara** [comment]
> Hi folks, thanks for the interest in our work! Really appreciate it!
> 
> Some amazing folks are working on implementing concept sliders on AUTOMATIC111 and comfyUI. Will keep you posted.

Awesome news

I also shared your articles on CivitAI Reddit LinkedIn Medium and Twitter

**Comment by fgtm2023** [comment]
> Hi folks, thanks for the interest in our work! Really appreciate it!
> 
> Some amazing folks are working on implementing concept sliders on AUTOMATIC111 and comfyUI. Will keep you posted.

great news, thanks a lot for this amazing work.

**Comment by rohitgandikota** [comment]
here is a similar issue that has a solution for a1111. closing this issue for now. Please reopen if necessary. Thanks for the interest! 

https://github.com/rohitgandikota/sliders/issues/2
