### ISSUE TITLE
Format for local pretrained model path?

### ISSUE THREAD

**Issue by TigonTX** [rohitgandikota/sliders#71]
Will support for https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1 be possible in the future?

**Comment by rohitgandikota** [comment]
That's a fantastic question! 

We haven't explored the img2vid models as much. But it is possible that there are some similarities in latent space. Currently our team is not focusing on video models, but I would be very happy to chat if someone is looking into it!

**Comment by phazei** [comment]
Any idea if you might be looking at this again?  Wan2.1 is pretty popular, sliders would be awesome for it

**Comment by rohitgandikota** [comment]
Working on a release for WAN2.1 and 2.2. 

Concept Sliders do work for video diffusion models. Cleaning up the repo and will plan a release hopefully next week

**Comment by phazei** [comment]
Hell yea!  Thank you :D

I'd be super curious on what you might be discovering on working with WAN 2.2 and how sliders could relate to motion.  It seems people have been training HIGH on more motion oriented things, and LOW on more detail things, like character LoRAs.  A slider that could increase/decrease motion would be incredibly useful if that's even conceptually in line with how this works.

**Comment by phazei** [comment]
@rohitgandikota  hey, how's it going?
