### ISSUE TITLE
Missing key(s) in state_dict: "text_model.embeddings.position_ids"

### ISSUE THREAD

**Issue by ChieVFX** [rohitgandikota/sliders#72]
Didn't work for me out of the box. :(
Outside of a few other issues (probably due to my existing python installation), one error I've spent some time on was:
"RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".

Fixed it by "pip install accelerate".

Maybe it should be added to the requirements.txt? If not, you can just close this issue.

Thank you for your hard work.

**Comment by rohitgandikota** [comment]
Huh, interesting! accelerate should not be a dependency that would fix issues with model parameters. But yes, I can definitely add accelerate to the requirements. Thanks for catching this issue and spending a lot of time on it!

**Comment by rohitgandikota** [comment]
done!
