### ISSUE TITLE
Sliders for generation

### ISSUE THREAD

**Issue by sauradip** [rohitgandikota/sliders#74]
Hi, 

Sorry in advance for asking a basic question. 

Can we use these trained LoRA for text2Image generation instead of Image editing ? let say "A silver jeep" here i train a LoRA using jeep as a target concept and make it interpolate between let say bright shaded and light shaded jeep , can that generate ?

**Comment by rohitgandikota** [comment]
Yes, image editing is one of the applications of sliders. But the main application is txt-2-img generation control. You can definitely use the sliders to control your text to image generations. Please refer to this notebook for the guide:
https://github.com/rohitgandikota/sliders/blob/main/XL-sliders-inference.ipynb
