### ISSUE TITLE
saving as safetentors

### ISSUE THREAD

**Issue by sbuldan** [rohitgandikota/sliders#80]
When I try to save as safetensors, it puts safetensors into the model name. Is there a way to save as safetensors?

**Comment by rohitgandikota** [comment]
yes! If you replace `.pt` with `.safetensors` here https://github.com/rohitgandikota/sliders/blob/b76a63e0df1da5fa51c15b3c68e0344ceb4fd095/trainscripts/textsliders/train_lora_xl.py#L373 - it should handle automatically. For the handling script please refer to this file: https://github.com/rohitgandikota/sliders/blob/b76a63e0df1da5fa51c15b3c68e0344ceb4fd095/trainscripts/textsliders/lora.py#L245
