### ISSUE TITLE
Why is running a text slider and a visual slider with the same 1k steps a text slider many times slower than a visual slider?

### ISSUE THREAD

**Issue by lixida123** [rohitgandikota/sliders#81]
Thank you for your work。
Why is running a text slider and a visual slider with the same 1k steps a text slider many times slower than a visual slider?

**Comment by rohitgandikota** [comment]
The training part is little different for visual sliders and text sliders. 

1. Visual sliders already have images to work with, so all they need to do is image inversion and optimize
2. Text sliders on the other hand need to generate an image partially and then work on it. 
3. Plus text sliders use 4 different concepts (target, unconditional, neutral, positive) whereas visual sliders use only 2 concepts to learn (positive, unconditional)

Hope that makes sense

**Comment by filliptm** [comment]
nice thanks for that, was wondering myself
