### ISSUE TITLE
Pretrained LoRa

### ISSUE THREAD

**Issue by Benji4564** [rohitgandikota/sliders#87]
I have a pretrained LoRa. Is it possible to use it and implement slider

**Comment by rohitgandikota** [comment]
Sure! You can load the LoRA before training starts and then continue the sliders training. This should be do-able

**Comment by Benji4564** [comment]
But am I have to load it behind the Stable Diffusion Pipeline in your loading script or does the LoRaNetwork class have to load it. Because as far as I remember the LoRa from kohya ss does not affect the unet but the decoder and you only use the Unet if I saw it correctly.

**Comment by Benji4564** [comment]
Another interesting thing would be the possibility to have mulitple different slider in one network

**Comment by rohitgandikota** [comment]
Yes! You can load the LoRA in any format before you start the sliders training. 

Also, we do talk about composing multiple sliders and even released a script to do it in one of the issues. Please do check it out!

**Comment by Benji4564** [comment]
Thanks for your help. I going to check it out. Do you have any tips for the training?  I tried to have a slider from formula 1 car to coupe, but it doesn't work out and the images for any rank looked the same

**Comment by chabrarahul** [comment]
Has anyone tried loading pre-trained LoRA for the sliders ?
