### ISSUE TITLE
meaning of the stylegan_latent sliders

### ISSUE THREAD

**Issue by eayumi** [rohitgandikota/sliders#9]
Hi! Great work!

I was wondering what kind of attributes the stylegan_latent1 and stylegan_latent2 sliders were editing. Are those the same as dscribed in the paper i.e. the cheekbone structure and inter-ocular distance?

**Comment by rohitgandikota** [comment]
Yes!

slider1 is from styleGAN-v3 Layer 4 Neuron 847 (which seems to control inter-ocular distance)
slider2 is from styleGAN-v3 Layer 4 Neuron 77 (which seems to control cheekbone placement vertically)
