### ISSUE TITLE
The structure of the image is not maintained in the SD1.4 text slider

### ISSUE THREAD

**Issue by sangh0Kim** [rohitgandikota/sliders#94]
@rohitgandikota Thank you for your wonderful code. I have one question to run the code.

The structure of the image is not maintained in the SD1.4 text slider. The text slider learned using SDXL maintains the shape of the initial image and only adds concept well. Why does it only have problems in SD1.4? Is there a solution?

Thank you.

**Comment by rohitgandikota** [comment]
Thanks! 

Did you try to reduce the `start_noise` parameter. That should help - we notice that SDXL representation space is large enough to maintain slightly more disentangled representations.

**Comment by sangh0Kim** [comment]
Thank you for your reply. I reduced the start_noise in SD v1.4 and confirmed that the structure of the initial image is maintained more.

I have one more question. Are the prompts you used to learn the pre-trained model yourself exactly the ones in the prompt-xl.yaml or prompt.yaml file? If I train the xl-slider using these prompts myself, it doesn't perform as well as the pre-trained models you shared. Is it because I didn't put the words '--attributes' for disentangle? How did you find the words for disentangle when you trained sliders like weather, night/day, indoor/outdoor? Please give me some tips on finding the words for disentangle.

Thank you!

**Comment by rohitgandikota** [comment]
Yes, especially for SDXL the attributes you use are going to play a very important role. You can use our GPT based prompt discovery notebook for easier prompt design

**Comment by rohitgandikota** [comment]
The usual norm is - for person related sliders use gender and races as attributes. It somehow helps for better slider training
